name: IconSalonSystems
favicon: null
layout_spectrum: 0.896
typography_spectrum: 0.62381
title: Icon Salon Systems - Bridging Business and Beauty
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#9e0b0f'
    - '#968b96'
    - '#ffffff'
    - '#555555'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
